CREATE TABLE CEP (
    CepID INT PRIMARY KEY,
    CepRua VARCHAR(150) NOT NULL,
    CepBairro VARCHAR(100) NOT NULL,
    CepCidade VARCHAR(100) NOT NULL,
    CepEstado CHAR(2) NOT NULL
);

CREATE TABLE ENDERECO (
    EndID INT PRIMARY KEY,
    EndComplemento VARCHAR(100),
    EndNumero VARCHAR(20) NOT NULL,
    CepID INT NOT NULL,
    CONSTRAINT fk_end_cep FOREIGN KEY (CepID) REFERENCES CEP (CepID)
);

CREATE TABLE USUARIO (
    UsrID INT PRIMARY KEY,
    UsrNome VARCHAR(150) NOT NULL,
    UsrCPF CHAR(11) NOT NULL UNIQUE,
    UsrDtNasc DATE NOT NULL
);

CREATE TABLE TELEFONE (
    TlfID INT PRIMARY KEY,
    TlfNumero VARCHAR(20) NOT NULL,
    UsrID INT NOT NULL,
    CONSTRAINT fk_tlf_usr FOREIGN KEY (UsrID) REFERENCES USUARIO (UsrID)
);

CREATE TABLE HOSPEDE (
    UsrID INT PRIMARY KEY,
    HosDataInicio DATE NOT NULL,
    CONSTRAINT fk_hos_usr FOREIGN KEY (UsrID) REFERENCES USUARIO (UsrID)
);

CREATE TABLE ANFITRIAO (
    UsrID INT PRIMARY KEY,
    AnfDataInicio DATE NOT NULL,
    CONSTRAINT fk_anf_usr FOREIGN KEY (UsrID) REFERENCES USUARIO (UsrID)
);

CREATE TABLE TIPOAV (
    TipoAvID INT PRIMARY KEY,
    TipoAVStr VARCHAR(50) NOT NULL
);

CREATE TABLE COMODIDADE (
    ComID INT PRIMARY KEY,
    ComNome VARCHAR(100) NOT NULL
);

CREATE TABLE ANUNCIO (
    AnID INT PRIMARY KEY,
    AnTitulo VARCHAR(200) NOT NULL,
    AnDesc TEXT NOT NULL,
    AnCustoDiaUtil NUMERIC(10,2) NOT NULL,
    AnCustoFimSem NUMERIC(10,2) NOT NULL,
    AcCapacPessoas INT NOT NULL,
    AcQtdQuartos INT NOT NULL,
    AcQtdBanheiros INT NOT NULL,
    EndID INT NOT NULL UNIQUE,
    AnfUsrID INT NOT NULL,
    CONSTRAINT fk_an_anf FOREIGN KEY (AnfUsrID) REFERENCES ANFITRIAO (UsrID),
    CONSTRAINT fk_an_end FOREIGN KEY (EndID) REFERENCES ENDERECO (EndID)
);

CREATE TABLE ACPOSSUICOM (
    AnID INT NOT NULL,
    ComID INT NOT NULL,
    PRIMARY KEY (AnID, ComID),
    CONSTRAINT fk_apc_an FOREIGN KEY (AnID) REFERENCES ANUNCIO (AnID),
    CONSTRAINT fk_apc_com FOREIGN KEY (ComID) REFERENCES COMODIDADE (ComID)
);

CREATE TABLE RESERVA (
    ResID INT PRIMARY KEY,
    ResDtIn DATE NOT NULL,
    ResDtOut DATE NOT NULL,
    ResStatus VARCHAR(30) NOT NULL,
    ResFormaPaga VARCHAR(30) NOT NULL,
    ResDataPaga DATE,
    ResQtdAdultos INT NOT NULL DEFAULT 1,
    ResQtdCriancas INT NOT NULL DEFAULT 0,
    ResQtdBebes INT NOT NULL DEFAULT 0,
    ResQtdPets INT NOT NULL DEFAULT 0,
    HosID INT NOT NULL,
    AnID INT NOT NULL,
    CONSTRAINT fk_res_hos FOREIGN KEY (HosID) REFERENCES HOSPEDE (UsrID),
    CONSTRAINT fk_res_an FOREIGN KEY (AnID) REFERENCES ANUNCIO (AnID)
);

CREATE TABLE AVALIACAO (
    AvID INT PRIMARY KEY,
    AvNota NUMERIC(3,1) NOT NULL,
    AvComentario TEXT,
    AvData DATE NOT NULL,
    AvTipo VARCHAR(30) NOT NULL,
    AnID INT NOT NULL,
    HosUsrID INT NOT NULL,
    TipoAvID INT NOT NULL,
    CONSTRAINT fk_av_an FOREIGN KEY (AnID) REFERENCES ANUNCIO (AnID),
    CONSTRAINT fk_av_hos FOREIGN KEY (HosUsrID) REFERENCES HOSPEDE (UsrID),
    CONSTRAINT fk_av_tipo FOREIGN KEY (TipoAvID) REFERENCES TIPOAV (TipoAvID)
);